backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: 'public/uploads' # Media files will be stored in the repo under images/uploads
public_folder: 'public/uploads'

collections:
  - name: 'frontpage' # Used in routes, e.g., /admin/collections/blog
    label: 'Frontpage' # Used in the UI
    folder: '_posts/frontpage' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Upcoming Streams'
        name: 'upcoming'
        widget: 'list'
        fields:
          - label: Streamer Name
            name: streamerName
            widget: string
          - label: Stream Link
            name: streamLink
            widget: string
          - label: Description
            name: descripion
            widget: string
          - label: Image
            name: imgUrl
            widget: image
          - label: Date
            name: date
            widget: datetime
