backend:
  name: git-gateway
  branch: release # Branch to update (optional; defaults to master)

media_folder: 'public/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/uploads'

collections:
  - name: 'pages' # Used in routes, e.g., /admin/collections/blog
    label: 'Pages' # Used in the UI
    files:
      - label: Charity Royale 2020
        name: cr2020
        file: _cms/charity-royale.md
        fields: # The fields for each document, usually in front matter
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
          - { label: 'Featured Stream', name: 'featuredStream', widget: 'string' }

          - label: 'Upcoming Streams'
            name: 'upcoming'
            widget: 'list'
            summary: '{{fields.streamerName}})'
            fields:
              - { label: 'Streamer Name', name: 'streamerName', widget: 'string' }
              - { label: 'Streamer Channel (Twitch username in lower case)', name: 'streamerChannel', widget: 'string' }
              - { label: 'Stream Link', name: 'streamLink', widget: 'string' }
              - { label: 'Streamer Image', name: 'imgUrl', widget: 'image' }
              - { label: 'Stream Date', name: 'date', widget: 'datetime' }
              - label: Make-a-Wish project
                name: makeAWishProjectId
                widget: string

          - label: Make-a-Wish projects
            name: 'makeAWishProjects'
            widget: list
            summary: '{{fields.makeAWishProjectId}} - {{fields.childname}}'
            fields:
              - { label: 'Project id (Make-a-wish)', name: 'makeAWishProjectId', widget: 'string' }
              - { label: 'Description', name: 'descripion', widget: 'string' }
              - { label: 'Tagline', name: 'tagline', widget: 'string' }
              - { label: 'Child Name', name: 'childname', widget: 'string' }

          - label: FAQ
            name: faq
            widget: object
            fields:
              - label: Questions
                name: questions
                widget: list
                fields:
                  - { label: 'Question', name: 'question', widget: 'string' }
                  - { label: 'Answer', name: 'answer', widget: 'markdown' }
              - label: Videos
                name: videos
                widget: list
                fields:
                  - { label: 'Video Url', name: 'url', widget: 'string' }
                  - { label: 'Video Name', name: 'name', widget: 'string' }
