backend:
  name: git-gateway
  branch: release # Branch to update (optional; defaults to master)

media_folder: 'public/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/uploads'

collections:
  - name: 'frontpage' # Used in routes, e.g., /admin/collections/blog
    label: 'Frontpage' # Used in the UI
    folder: '_posts/frontpage' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Featured Stream', name: 'featuredStream', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: FAQ
        name: faq
        widget: list
        fields:
          - label: Question
            name: question
            widget: string
          - label: Answer
            name: answer
            widget: string
      - label: FAQ Videos
        name: faqvideos
        widget: list
        fields:
          - label: Video Url
            name: url
            widget: string
          - label: Video Name
            name: name
            widget: string
      - label: 'Upcoming Streams'
        name: 'upcoming'
        widget: 'list'
        fields:
          - label: Streamer Name
            name: streamerName
            widget: string
          - label: Streamer Channel (Twitch username in lower case)
            name: streamerChannel
            widget: string
          - label: Stream Link
            name: streamLink
            widget: string
          - label: Streamer Image
            name: imgUrl
            widget: image
          - label: Stream Date
            name: date
            widget: datetime
          - label: Project id (Make-a-wish)
            name: makeAWishProjectId
            widget: string
          - label: Description
            name: descripion
            widget: string
          - label: Tagline
            name: tagline
            widget: string
          - label: Child Name
            name: childname
            widget: string
