name: Node.js CI

on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v1
         with:
           node-version: ${{ matrix.node-version }}
       - run: npm install
       - name: Create .env.local file
         run: |
           touch .env.local
           echo TWITCH_ACCESS_TOKEN=${{ secrets.TWITCH_ACCESS_TOKEN }} >> .env.local
           echo TWITCH_CLIENT_ID=${{ secrets.TWITCH_CLIENT_ID }} >> .env.local
           echo GA_ID=${{ secrets.GA_ID }} >> .env.local
           echo FB_ID=${{ secrets.FB_ID }} >> .env.local
       - name: Build it pls
         run: node ./scripts/generateICSfiles.js && npx next build && npx next export
       - name: Lint
         run: npx eslint src --ext .ts,.tsx
